ALTER TABLE POSTAL
ADD CONSTRAINT buildingno_pk PRIMARY KEY(BUILDINGNO)
;
ALTER TABLE CUSTOMER
ADD buildingno VARCHAR2(25)
;
ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_buildingno_fk FOREIGN KEY(buildingno) REFERENCES POSTAL(BUILDINGNO) 
;

select * from customer
;

ALTER TABLE CUSTOMER
ADD addr VARCHAR2(40)
;

commit;
